@startuml
'https://plantuml.com/class-diagram

class Application {
    String inputFileName
    FileIO myFile
    String[] fileContents
    RecordParser myParser
    String[][] myTable
    main()
    readList()
    printTable()
}

class FileIO {
    -File inputFile
    +setInputFile()
    +closeInput()
    +readFromFile()
    +writeToFile()
}

class RecordParser {
    -String[] recordsList
    -String[][] recordsTable
    +RecordParser()
    +fillTable()
    +getTable()
}

@enduml