@startuml
'https://plantuml.com/class-diagram

class Application {
    String inputFileName
    String outputFileName
    FileIO myFile
    nameList: String List
    NameManager nameSet
}

class FileIO {
    -File inputFile
    +FileIO()
    +closeInput()
    +readFromFile()
    +writeToFile()
}

class NameManager {
    -nameList: String List
    +getNames()
    +setNames()
    +sortAlpha()
}

Application <-> FileIO
Application <--> NameManager

@enduml