@startuml
'https://plantuml.com/class-diagram

class Application {
    main()
    readList()
    writeList()
}

class FileIO {
    -File inputFile
    +setInputFile()
    +closeInput()
    +readFromFile()
    +writeToFile()
}

class NameManager {
    -nameList: String List
    +getNames()
    +setNames()
    +sortAlpha()
}

@enduml